# Generated by Django 3.1 on 2020-09-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='images/testimony')),
                ('testimony', models.TextField()),
                ('show', models.BooleanField(default=False)),
            ],
        ),
    ]
